version: '3'
services:
  master:
    image: redis:6.0.5
    container_name: redis-master
    command: redis-server  --requirepass 123456  --masterauth 123456
    ports:
      - 6380:6379
  slave1:
    image: redis:6.0.5
    container_name: redis-slave-1
    ports:
      - 6381:6379
    command:  redis-server --slaveof redis-master 6379 --masterauth 123456  --requirepass 123456
  slave2:
    image: redis:6.0.5
    container_name: redis-slave-2
    ports:
      - 6382:6379
    command: redis-server --slaveof redis-master 6379 --masterauth 123456 --requirepass 123456