version: '3.0'
services:
  rabbitmq3:
    image: "rabbitmq:3.8-management"
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
      - "25672:25672"
