# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres:12.3
    container_name: postgres
    ports: 
      - 5432:5432
    # restart: always
    environment:
      POSTGRES_USER: gkd
      POSTGRES_PASSWORD: gkd
      POSTGRES_DB: gkd_db
    volumes:
      - ${PWD}/database-data:/var/lib/postgresql/data/
#   pg_adminer:
#     image: adminer:4.7.7
#     # restart: always
#     ports:
#       - 9999:9999