version: '3.0'
services:
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "password"]
    hostname: redis
    ports:
      - 6179:6379
    volumes:
      - ./redis-data:/data
